let data = [
  {
    id: "2020_1",
    name: "Student 1",
    email: "student1@college.com",
    contact: "9879871001",
    gender: "Male",
    adYear: 2020,
    merit: 82,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2021_2",
    name: "Student 2",
    email: "student2@college.com",
    contact: "9879871002",
    gender: "Male",
    adYear: 2021,
    merit: 90,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2022_3",
    name: "Student 3",
    email: "student3@college.com",
    contact: "9879871003",
    gender: "Female",
    adYear: 2022,
    merit: 90,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2023_4",
    name: "Student 4",
    email: "student4@college.com",
    contact: "9879871004",
    gender: "Male",
    adYear: 2023,
    merit: 73,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2019_5",
    name: "Student 5",
    email: "student5@college.com",
    contact: "9879871005",
    gender: "Male",
    adYear: 2019,
    merit: 81,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2020_6",
    name: "Student 6",
    email: "student6@college.com",
    contact: "9879871006",
    gender: "Female",
    adYear: 2020,
    merit: 89,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2021_7",
    name: "Student 7",
    email: "student7@college.com",
    contact: "9879871007",
    gender: "Male",
    adYear: 2021,
    merit: 85,
    adCat: "D2D",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2022_8",
    name: "Student 8",
    email: "student8@college.com",
    contact: "9879871008",
    gender: "Male",
    adYear: 2022,
    merit: 88,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2023_9",
    name: "Student 9",
    email: "student9@college.com",
    contact: "9879871009",
    gender: "Female",
    adYear: 2023,
    merit: 76,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2019_10",
    name: "Student 10",
    email: "student10@college.com",
    contact: "9879871010",
    gender: "Male",
    adYear: 2019,
    merit: 93,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2020_11",
    name: "Student 11",
    email: "student11@college.com",
    contact: "9879871011",
    gender: "Male",
    adYear: 2020,
    merit: 72,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2021_12",
    name: "Student 12",
    email: "student12@college.com",
    contact: "9879871012",
    gender: "Female",
    adYear: 2021,
    merit: 86,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2022_13",
    name: "Student 13",
    email: "student13@college.com",
    contact: "9879871013",
    gender: "Male",
    adYear: 2022,
    merit: 75,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2023_14",
    name: "Student 14",
    email: "student14@college.com",
    contact: "9879871014",
    gender: "Male",
    adYear: 2023,
    merit: 87,
    adCat: "D2D",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2019_15",
    name: "Student 15",
    email: "student15@college.com",
    contact: "9879871015",
    gender: "Female",
    adYear: 2019,
    merit: 67,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2020_16",
    name: "Student 16",
    email: "student16@college.com",
    contact: "9879871016",
    gender: "Male",
    adYear: 2020,
    merit: 65,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2021_17",
    name: "Student 17",
    email: "student17@college.com",
    contact: "9879871017",
    gender: "Male",
    adYear: 2021,
    merit: 81,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2022_18",
    name: "Student 18",
    email: "student18@college.com",
    contact: "9879871018",
    gender: "Female",
    adYear: 2022,
    merit: 71,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2023_19",
    name: "Student 19",
    email: "student19@college.com",
    contact: "9879871019",
    gender: "Male",
    adYear: 2023,
    merit: 78,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2019_20",
    name: "Student 20",
    email: "student20@college.com",
    contact: "9879871020",
    gender: "Male",
    adYear: 2019,
    merit: 66,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2020_21",
    name: "Student 21",
    email: "student21@college.com",
    contact: "9879871021",
    gender: "Female",
    adYear: 2020,
    merit: 70,
    adCat: "D2D",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2021_22",
    name: "Student 22",
    email: "student22@college.com",
    contact: "9879871022",
    gender: "Male",
    adYear: 2021,
    merit: 80,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2022_23",
    name: "Student 23",
    email: "student23@college.com",
    contact: "9879871023",
    gender: "Male",
    adYear: 2022,
    merit: 73,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2023_24",
    name: "Student 24",
    email: "student24@college.com",
    contact: "9879871024",
    gender: "Female",
    adYear: 2023,
    merit: 85,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2019_25",
    name: "Student 25",
    email: "student25@college.com",
    contact: "9879871025",
    gender: "Male",
    adYear: 2019,
    merit: 71,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2020_26",
    name: "Student 26",
    email: "student26@college.com",
    contact: "9879871026",
    gender: "Male",
    adYear: 2020,
    merit: 92,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2021_27",
    name: "Student 27",
    email: "student27@college.com",
    contact: "9879871027",
    gender: "Female",
    adYear: 2021,
    merit: 89,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2022_28",
    name: "Student 28",
    email: "student28@college.com",
    contact: "9879871028",
    gender: "Male",
    adYear: 2022,
    merit: 70,
    adCat: "D2D",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2023_29",
    name: "Student 29",
    email: "student29@college.com",
    contact: "9879871029",
    gender: "Male",
    adYear: 2023,
    merit: 83,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2019_30",
    name: "Student 30",
    email: "student30@college.com",
    contact: "9879871030",
    gender: "Female",
    adYear: 2019,
    merit: 66,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2020_31",
    name: "Student 31",
    email: "student31@college.com",
    contact: "9879871031",
    gender: "Male",
    adYear: 2020,
    merit: 71,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2021_32",
    name: "Student 32",
    email: "student32@college.com",
    contact: "9879871032",
    gender: "Male",
    adYear: 2021,
    merit: 74,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2022_33",
    name: "Student 33",
    email: "student33@college.com",
    contact: "9879871033",
    gender: "Female",
    adYear: 2022,
    merit: 92,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2023_34",
    name: "Student 34",
    email: "student34@college.com",
    contact: "9879871034",
    gender: "Male",
    adYear: 2023,
    merit: 75,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2019_35",
    name: "Student 35",
    email: "student35@college.com",
    contact: "9879871035",
    gender: "Male",
    adYear: 2019,
    merit: 91,
    adCat: "D2D",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2020_36",
    name: "Student 36",
    email: "student36@college.com",
    contact: "9879871036",
    gender: "Female",
    adYear: 2020,
    merit: 94,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2021_37",
    name: "Student 37",
    email: "student37@college.com",
    contact: "9879871037",
    gender: "Male",
    adYear: 2021,
    merit: 88,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2022_38",
    name: "Student 38",
    email: "student38@college.com",
    contact: "9879871038",
    gender: "Male",
    adYear: 2022,
    merit: 68,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2023_39",
    name: "Student 39",
    email: "student39@college.com",
    contact: "9879871039",
    gender: "Female",
    adYear: 2023,
    merit: 92,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2019_40",
    name: "Student 40",
    email: "student40@college.com",
    contact: "9879871040",
    gender: "Male",
    adYear: 2019,
    merit: 82,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2020_41",
    name: "Student 41",
    email: "student41@college.com",
    contact: "9879871041",
    gender: "Male",
    adYear: 2020,
    merit: 70,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2021_42",
    name: "Student 42",
    email: "student42@college.com",
    contact: "9879871042",
    gender: "Female",
    adYear: 2021,
    merit: 68,
    adCat: "D2D",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2022_43",
    name: "Student 43",
    email: "student43@college.com",
    contact: "9879871043",
    gender: "Male",
    adYear: 2022,
    merit: 95,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2023_44",
    name: "Student 44",
    email: "student44@college.com",
    contact: "9879871044",
    gender: "Male",
    adYear: 2023,
    merit: 93,
    adCat: "Regular",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2019_45",
    name: "Student 45",
    email: "student45@college.com",
    contact: "9879871045",
    gender: "Female",
    adYear: 2019,
    merit: 94,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2020_46",
    name: "Student 46",
    email: "student46@college.com",
    contact: "9879871046",
    gender: "Male",
    adYear: 2020,
    merit: 78,
    adCat: "Regular",
    collage: "S. V. Institute",
    department: "Civil",
    depHead: "Rahul Dravid",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  {
    id: "2021_47",
    name: "Student 47",
    email: "student47@college.com",
    contact: "9879871047",
    gender: "Male",
    adYear: 2021,
    merit: 85,
    adCat: "Regular",
    collage: "Nirma University",
    department: "Mechanical",
    depHead: "Kapil Dev",
    yearHead: "Nidhi Joshi",
    year: "Fourth",
  },
  {
    id: "2022_48",
    name: "Student 48",
    email: "student48@college.com",
    contact: "9879871048",
    gender: "Female",
    adYear: 2022,
    merit: 93,
    adCat: "Regular",
    collage: "Silver Oak College",
    department: "Automobile",
    depHead: "Sachin Tendulkar",
    yearHead: "Devendra Thakor",
    year: "First",
  },
  {
    id: "2023_49",
    name: "Student 49",
    email: "student49@college.com",
    contact: "9879871049",
    gender: "Male",
    adYear: 2023,
    merit: 81,
    adCat: "D2D",
    collage: "GEC Rajkot",
    department: "Electrical",
    depHead: "Anil Kumble",
    yearHead: "Rachana Patel",
    year: "Second",
  },
  {
    id: "2019_50",
    name: "Student 50",
    email: "student50@college.com",
    contact: "9879871050",
    gender: "Male",
    adYear: 2019,
    merit: 100,
    adCat: "Regular",
    collage: "L. E. Collage",
    department: "Computer",
    depHead: "M.S. Dhoni",
    yearHead: "Jignesh Shah",
    year: "Third",
  },
  //  {
  //0   id: "2019_50",
  //1   name: "Student 50",
  //2   email: "student50@college.com",
  //3   contact: "9879871050",
  //4   gender: "Male",
  //5   adYear: 2019,
  //6   merit: 71,
  //7   adCat: "Regular",
  //8   collage: "L. E. Collage",
  //9   department: "Computer",
  //10   depHead: "M.S. Dhoni",
  //11   yearHead: "Jignesh Shah",
  //12   year: "Third",
  // },
];

function loadTable() {
  const tableBody = document.getElementById("tableBody");
  tableBody.innerHTML = "";
  data.forEach((info) => {
    const row = document.createElement("tr");
    row.innerHTML = `
          <td>${info.id}</td>
          <td>${info.name}</td>
          <td>${info.email}</td>
          <td>${info.contact}</td>
          <td>${info.gender}</td>
          <td>${info.adYear}</td>
          <td>${info.merit}</td>
          <td>${info.adCat}</td>
          <td>${info.collage}</td>
          <td>${info.department}</td>
          <td>${info.depHead}</td>
          <td>${info.yearHead}</td>
          <td>${info.year}</td>
        `;
    tableBody.appendChild(row);
  });
}

function Filter() {
  const genderValue = document.getElementById("filter-gender").value;
  const departmentValue = document.getElementById("filter-department").value;
  const YearValue = document.getElementById("filter-Year").value;
  const admissionValue = document.getElementById("filter-admission").value;
  const meritValue = document.getElementById("filter-merit").value;
  const meritValues = document.getElementById("meritInput").value;
 
  const rows = document.querySelectorAll("tbody tr");
  
  rows.forEach((row) => {
    const gender = row.children[4].textContent.toLowerCase();
    const department = row.children[9].textContent.toLowerCase();
    const yearAll = row.children[12].textContent.toLowerCase();
    const admission = row.children[5].textContent;
    const merit = row.children[6].textContent;
    const inputMerit = row.children[6].textContent;

    const genderMatch = genderValue === "" || gender === genderValue;
    const departmentMatch = departmentValue === "" || department === departmentValue;
    const yearMatch = YearValue === "" || yearAll === YearValue;
    const admissionMatch = admissionValue === "" || admission === admissionValue;
    const meritMatchInput  = meritValues === "" || inputMerit === meritValues;

    if (meritValue !== 0 ) {

      switch (meritValue) {
        case "":
          meritMatch = merit >=0 && merit <=100 
          break;
        case "60":
          meritMatch = merit >= 60 && merit <= 70;
          break;
        case "70":
          meritMatch = merit >= 71 && merit <= 80;
          break;
        case "80":
          meritMatch = merit >= 81 && merit <= 90;
          break;
        case "90":
          meritMatch = merit >= 91 && merit <= 100;
          break;
      }
    }
    if (genderMatch && departmentMatch && yearMatch && admissionMatch && meritMatch && meritMatchInput) {
      row.style.display = "";
    } else {
      row.style.display = "none";
    }
  });
}

  document.getElementById("meritInput").addEventListener("change", function (e) {
    console.log('working');
    
    const serchData = e.target.value;
    const filterData = data.filter((info) => {
        const store =  info.merit.includes(serchData);        
    });    
    if (filterData) {
      console.log(filterData);
      search(filterData);
    }
  }); 


document.getElementById("filter-gender").addEventListener("change", Filter);
document.getElementById("filter-department").addEventListener("change", Filter);
document.getElementById("filter-Year").addEventListener("change", Filter);
document.getElementById("filter-admission").addEventListener("change", Filter);
document.getElementById("filter-merit").addEventListener("change", Filter);
document.getElementById("meritInput").addEventListener("change",Filter);

function tableReset() {
  document.getElementById("filter-gender").value = "";
  document.getElementById("filter-department").value = "";
  document.getElementById("filter-Year").value = "";
  document.getElementById("filter-admission").value = "";
  document.getElementById("filter-merit").value = "";
  document.getElementById("meritInput").value ="";
  Filter();
}

function downloadPDF() {
  const doc = new window.jspdf.jsPDF();
  doc.autoTable({ html: "#dataTable" });
  doc.save("college_data.pdf");
}
loadTable();